on: [push]

jobs:
  url_shortener:
    runs-on: ubuntu-latest
    name: Short URLs
    steps:
    - name: shortener
      id: shortener
      uses: Gottox/url-shortener-action@main
      with:
        url: "${{ github.event.compare }}"
    - name: outputs
      run: echo "${{ steps.shortener.outputs.short_url }}"
